"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.commit_meta import CommitMeta
from gitea.model.commit_user import CommitUser
globals()['CommitMeta'] = CommitMeta
globals()['CommitUser'] = CommitUser
from gitea.model.repo_commit import RepoCommit


class TestRepoCommit(unittest.TestCase):
    """RepoCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoCommit(self):
        """Test RepoCommit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepoCommit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
