"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.git_blob_response import GitBlobResponse


class TestGitBlobResponse(unittest.TestCase):
    """GitBlobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitBlobResponse(self):
        """Test GitBlobResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GitBlobResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
