"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.create_pull_review_comment import CreatePullReviewComment
globals()['CreatePullReviewComment'] = CreatePullReviewComment
from gitea.model.create_pull_review_options import CreatePullReviewOptions


class TestCreatePullReviewOptions(unittest.TestCase):
    """CreatePullReviewOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePullReviewOptions(self):
        """Test CreatePullReviewOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePullReviewOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
