"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.payload_user import PayloadUser
globals()['PayloadUser'] = PayloadUser
from gitea.model.payload_commit_verification import PayloadCommitVerification


class TestPayloadCommitVerification(unittest.TestCase):
    """PayloadCommitVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadCommitVerification(self):
        """Test PayloadCommitVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadCommitVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
