"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.annotated_tag_object import AnnotatedTagObject


class TestAnnotatedTagObject(unittest.TestCase):
    """AnnotatedTagObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotatedTagObject(self):
        """Test AnnotatedTagObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotatedTagObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
