"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.payload_commit_verification import PayloadCommitVerification
from gitea.model.payload_user import PayloadUser
globals()['PayloadCommitVerification'] = PayloadCommitVerification
globals()['PayloadUser'] = PayloadUser
from gitea.model.payload_commit import PayloadCommit


class TestPayloadCommit(unittest.TestCase):
    """PayloadCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadCommit(self):
        """Test PayloadCommit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadCommit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
