"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.issue_deadline import IssueDeadline


class TestIssueDeadline(unittest.TestCase):
    """IssueDeadline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueDeadline(self):
        """Test IssueDeadline"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueDeadline()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
