"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.issue_template import IssueTemplate


class TestIssueTemplate(unittest.TestCase):
    """IssueTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueTemplate(self):
        """Test IssueTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
