"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.edit_git_hook_option import EditGitHookOption


class TestEditGitHookOption(unittest.TestCase):
    """EditGitHookOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditGitHookOption(self):
        """Test EditGitHookOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditGitHookOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
