"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.external_tracker import ExternalTracker
from gitea.model.external_wiki import ExternalWiki
from gitea.model.internal_tracker import InternalTracker
globals()['ExternalTracker'] = ExternalTracker
globals()['ExternalWiki'] = ExternalWiki
globals()['InternalTracker'] = InternalTracker
from gitea.model.edit_repo_option import EditRepoOption


class TestEditRepoOption(unittest.TestCase):
    """EditRepoOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditRepoOption(self):
        """Test EditRepoOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditRepoOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
