"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.issue import Issue
globals()['Issue'] = Issue
from gitea.model.tracked_time import TrackedTime


class TestTrackedTime(unittest.TestCase):
    """TrackedTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackedTime(self):
        """Test TrackedTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrackedTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
