"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.file_links_response import FileLinksResponse
globals()['FileLinksResponse'] = FileLinksResponse
from gitea.model.contents_response import ContentsResponse


class TestContentsResponse(unittest.TestCase):
    """ContentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentsResponse(self):
        """Test ContentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
