"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.user import User
globals()['User'] = User
from gitea.model.reaction import Reaction


class TestReaction(unittest.TestCase):
    """Reaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReaction(self):
        """Test Reaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Reaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
