"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.team import Team
globals()['Team'] = Team
from gitea.model.team_search200_response import TeamSearch200Response


class TestTeamSearch200Response(unittest.TestCase):
    """TeamSearch200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamSearch200Response(self):
        """Test TeamSearch200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeamSearch200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
