"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.o_auth2_application import OAuth2Application


class TestOAuth2Application(unittest.TestCase):
    """OAuth2Application unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Application(self):
        """Test OAuth2Application"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuth2Application()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
