"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.create_pull_request_option import CreatePullRequestOption


class TestCreatePullRequestOption(unittest.TestCase):
    """CreatePullRequestOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePullRequestOption(self):
        """Test CreatePullRequestOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePullRequestOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
