"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.user import User
globals()['User'] = User
from gitea.model.public_key import PublicKey


class TestPublicKey(unittest.TestCase):
    """PublicKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicKey(self):
        """Test PublicKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PublicKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
