"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.file_commit_response import FileCommitResponse
from gitea.model.payload_commit_verification import PayloadCommitVerification
globals()['FileCommitResponse'] = FileCommitResponse
globals()['PayloadCommitVerification'] = PayloadCommitVerification
from gitea.model.file_delete_response import FileDeleteResponse


class TestFileDeleteResponse(unittest.TestCase):
    """FileDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileDeleteResponse(self):
        """Test FileDeleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FileDeleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
