"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.create_o_auth2_application_options import CreateOAuth2ApplicationOptions


class TestCreateOAuth2ApplicationOptions(unittest.TestCase):
    """CreateOAuth2ApplicationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOAuth2ApplicationOptions(self):
        """Test CreateOAuth2ApplicationOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateOAuth2ApplicationOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
