"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.external_tracker import ExternalTracker
from gitea.model.external_wiki import ExternalWiki
from gitea.model.internal_tracker import InternalTracker
from gitea.model.permission import Permission
from gitea.model.user import User
globals()['ExternalTracker'] = ExternalTracker
globals()['ExternalWiki'] = ExternalWiki
globals()['InternalTracker'] = InternalTracker
globals()['Permission'] = Permission
globals()['User'] = User
from gitea.model.repository import Repository


class TestRepository(unittest.TestCase):
    """Repository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepository(self):
        """Test Repository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Repository()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
