"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.user import User
globals()['User'] = User
from gitea.model.commit_status import CommitStatus


class TestCommitStatus(unittest.TestCase):
    """CommitStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommitStatus(self):
        """Test CommitStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommitStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
