"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.commit_affected_files import CommitAffectedFiles
from gitea.model.commit_meta import CommitMeta
from gitea.model.repo_commit import RepoCommit
from gitea.model.user import User
globals()['CommitAffectedFiles'] = CommitAffectedFiles
globals()['CommitMeta'] = CommitMeta
globals()['RepoCommit'] = RepoCommit
globals()['User'] = User
from gitea.model.commit import Commit


class TestCommit(unittest.TestCase):
    """Commit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommit(self):
        """Test Commit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Commit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
