"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.delete_email_option import DeleteEmailOption


class TestDeleteEmailOption(unittest.TestCase):
    """DeleteEmailOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteEmailOption(self):
        """Test DeleteEmailOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteEmailOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
