"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.notification_subject import NotificationSubject
from gitea.model.repository import Repository
globals()['NotificationSubject'] = NotificationSubject
globals()['Repository'] = Repository
from gitea.model.notification_thread import NotificationThread


class TestNotificationThread(unittest.TestCase):
    """NotificationThread unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationThread(self):
        """Test NotificationThread"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationThread()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
