"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.user import User
globals()['User'] = User
from gitea.model.user_search200_response import UserSearch200Response


class TestUserSearch200Response(unittest.TestCase):
    """UserSearch200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserSearch200Response(self):
        """Test UserSearch200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserSearch200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
