"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.internal_tracker import InternalTracker


class TestInternalTracker(unittest.TestCase):
    """InternalTracker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternalTracker(self):
        """Test InternalTracker"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InternalTracker()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
