"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.user import User
globals()['User'] = User
from gitea.model.pull_review_comment import PullReviewComment


class TestPullReviewComment(unittest.TestCase):
    """PullReviewComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullReviewComment(self):
        """Test PullReviewComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PullReviewComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
