"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.team import Team
from gitea.model.user import User
globals()['Team'] = Team
globals()['User'] = User
from gitea.model.pull_review import PullReview


class TestPullReview(unittest.TestCase):
    """PullReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullReview(self):
        """Test PullReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PullReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
