"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.label import Label
from gitea.model.milestone import Milestone
from gitea.model.pr_branch_info import PRBranchInfo
from gitea.model.user import User
globals()['Label'] = Label
globals()['Milestone'] = Milestone
globals()['PRBranchInfo'] = PRBranchInfo
globals()['User'] = User
from gitea.model.pull_request import PullRequest


class TestPullRequest(unittest.TestCase):
    """PullRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullRequest(self):
        """Test PullRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PullRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
