"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.annotated_tag_object import AnnotatedTagObject
from gitea.model.commit_user import CommitUser
from gitea.model.payload_commit_verification import PayloadCommitVerification
globals()['AnnotatedTagObject'] = AnnotatedTagObject
globals()['CommitUser'] = CommitUser
globals()['PayloadCommitVerification'] = PayloadCommitVerification
from gitea.model.annotated_tag import AnnotatedTag


class TestAnnotatedTag(unittest.TestCase):
    """AnnotatedTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotatedTag(self):
        """Test AnnotatedTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotatedTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
