"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gitea
from gitea.model.pull_review_request_options import PullReviewRequestOptions


class TestPullReviewRequestOptions(unittest.TestCase):
    """PullReviewRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullReviewRequestOptions(self):
        """Test PullReviewRequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PullReviewRequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
