# flake8: noqa

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.14.6
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from gitea.api_client import ApiClient

# import Configuration
from gitea.configuration import Configuration

# import exceptions
from gitea.exceptions import OpenApiException
from gitea.exceptions import ApiAttributeError
from gitea.exceptions import ApiTypeError
from gitea.exceptions import ApiValueError
from gitea.exceptions import ApiKeyError
from gitea.exceptions import ApiException
