# Generated by Django 4.1.3 on 2022-12-10 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsetting',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='porter.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('user', 'project')},
        ),
        migrations.CreateModel(
            name='BuildTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'CANCELED'), (5, 'TIMEOUT'), (6, 'CANCELING')], default=0)),
                ('version', models.CharField(max_length=128)),
                ('commit', models.CharField(max_length=40)),
                ('yaml', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'version')},
            },
        ),
    ]
