# Generated by Django 4.1.3 on 2022-12-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0002_alter_buildsetting_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('message', models.TextField()),
                ('committer_name', models.CharField(max_length=64)),
                ('committer_email', models.CharField(max_length=64)),
                ('committed_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='buildtask',
            old_name='commit',
            new_name='commit_sha',
        ),
    ]
