# Generated by Django 4.1.3 on 2022-12-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0003_commit_rename_commit_buildtask_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildtask',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='porter.commit'),
        ),
    ]
