# Generated by Django 4.1.3 on 2022-12-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0004_buildtask_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildtask',
            name='log',
            field=models.TextField(null=True),
        ),
    ]
