# Generated by Django 4.1.3 on 2022-12-31 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porter', '0006_buildtask_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
                ('description', models.CharField(max_length=255)),
                ('config', models.TextField()),
                ('registry', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
                ('namespace', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
                ('template', models.TextField(null=True)),
                ('replicas', models.IntegerField(default=1)),
                ('cpu_limit', models.PositiveBigIntegerField(default=2000)),
                ('memory_limit', models.PositiveBigIntegerField(default=4000)),
                ('cpu_request', models.PositiveBigIntegerField(default=1000)),
                ('memory_request', models.PositiveBigIntegerField(default=2000)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.cluster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')]),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.stage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=128)),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'CANCELED'), (5, 'TIMEOUT'), (6, 'CANCELING')], default=0)),
                ('yaml', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('generation', models.TextField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deployment_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.deploymentunit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deploymentunit',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.lane'),
        ),
        migrations.AddField(
            model_name='deploymentunit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.project'),
        ),
        migrations.AddField(
            model_name='deploymentunit',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.stage'),
        ),
        migrations.AddField(
            model_name='deploymentunit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentunit',
            unique_together={('project_id', 'cluster_id', 'namespace')},
        ),
    ]
