# Generated by Django 4.1.3 on 2023-01-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0007_cluster_deploymentunit_alter_project_name_stage_lane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploytask',
            name='generation',
            field=models.IntegerField(default=0),
        ),
    ]
