# Generated by Django 4.1.3 on 2023-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0008_alter_deploytask_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploytask',
            options={'ordering': ['-created_at', '-generation']},
        ),
        migrations.AddField(
            model_name='deploymentunit',
            name='progress_deadline',
            field=models.PositiveBigIntegerField(default=600),
        ),
    ]
