# Generated by Django 4.1.3 on 2023-01-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0009_alter_deploytask_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lane',
            unique_together={('stage', 'name')},
        ),
    ]
