# Generated by Django 4.1.3 on 2023-01-02 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porter', '0011_alter_deploymentunit_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lane',
            options={'ordering': ['index', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['index', '-created_at']},
        ),
        migrations.AddField(
            model_name='lane',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='strict',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentunit',
            unique_together={('project', 'cluster', 'namespace'), ('project', 'lane')},
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=128)),
                ('closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='porter.deploytask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porter.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deploytask',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='porter.pipeline'),
        ),
    ]
