# Generated by Django 4.1.3 on 2023-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0012_alter_lane_options_alter_stage_options_lane_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='stage',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lane',
            unique_together={('stage', 'name'), ('stage', 'index')},
        ),
    ]
