# Generated by Django 4.1.3 on 2022-11-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0002_repository_created_at_repository_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='content',
        ),
        migrations.AddField(
            model_name='repository',
            name='git_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
