# Generated by Django 4.1.3 on 2022-11-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0008_periodictask_task_periodic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='uid',
            field=models.UUIDField(unique=True),
        ),
    ]
