# Generated by Django 4.1.3 on 2022-12-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0009_alter_periodictask_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='envvars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='extravars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='inventories',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='envvars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='extravars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='inventories',
            field=models.TextField(blank=True, default=''),
        ),
    ]
